aa1<-read.csv("fb.csv")
aa2<-read.csv("fb_1.csv")
new_dataset = rbind(aa1,aa2)
View(new_dataset)
dim(new_dataset)
aa3<-order(-aa1$category)
View(head(aa3))
write.csv(aa3,"newfb.csv")
r5 = read.csv("newfb.csv")
